# ========================
# Jekyll Configuration File
# AR-Website (Anime/Tech/Movies)
# ========================

# Site Identity
title: "AR Hub - Anime, Tech & Movies"
description: "Your ultimate destination for anime reviews, tech blogs and movie updates!"
url: "https://ar247.netlify.app"  # Replace with your URL
baseurl: ""  # Leave empty for Netlify

include:
  - admin

# Technical Settings
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: Asia/Kolkata

# Build Settings
collections_dir: .
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Default Front Matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      category: "general"
      tags: []

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

  tags:
    output: true
    permalink: /tags/:name/

# Sitemap
sitemap:
  changefreq: weekly
  priority: 0.8

# Developer Mode
safe: true
incremental: false
