title: AR Website
description: Your Hub for Anime, Movies, and Tech Blogs
baseurl: ""
url: "https://ar24.netlify.app"
collections:
  posts:
    output: true

plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-seo-tag

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
