source "https://rubygems.org"

gem "jekyll", "~> 4.3.3"
gem "webrick"
gem "nokogiri", "~> 1.16"
gem "jekyll-paginate-v2"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "minima", "~> 2.5"
gem "csv"
gem "base64"
ruby "3.4.2"
