backend:
  name: git-gateway
  branch: main  # Tumhara GitHub branch (usually "main")

media_folder: "assets/images/uploads"  # Media files ka location

collections:
  - name: "posts"  # Blog posts ke liye
    label: "Posts"
    folder: "_posts"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "body", label: "Content", widget: "markdown" }