# admin/config.yml
backend:
  name: git-gateway
  branch: main

media_folder: assets/images/uploads

collections:
  - name: posts
    label: Posts
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Content, widget: markdown }
